config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'evidencias' , to: 'welcome#evidencias', as: 'evidencias'
  resources :projects

  root 'welcome#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belogns_to :project
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :projects
	has_many :categories
	belongs_to :category
end

app/models/experience.rb
class Experience < ActiveRecord::Base
	belogs_to :user
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :userGroups
	has_many :users, through: :userGroups
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :users
	has_many :users, through: :userProjects
	belongs_to :category
end

app/models/rank.rb
class Rank < ActiveRecord::Base
	has_many :users
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 	has_many :userGroups
	has_many :groups, through: :userGroups
	has_many :projects
	has_many :projects, through: :userProjects
	has_many :skills
	has_many :experiences
  belongs_to :rank
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/user_project.rb
class UserProject < ActiveRecord::Base
	belongs_to :user
	belongs_to :project
	has_many :activities
end

app/controllers/SCOPE/confirmations_controller.rb
class SCOPE::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/SCOPE/passwords_controller.rb
class SCOPE::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/SCOPE/sessions_controller.rb
class SCOPE::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/SCOPE/unlocks_controller.rb
class SCOPE::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new

  end

  def index
    @projects = Project.all
    @project = Project.new
  end

  def create
    Project.create(pro_params)
    redirect_to projects_path
  end

  def update
  end

  def destroy
  end

  def show
  end
  def pro_params
     params.require(:project).permit(:title, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def evidencias
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>NewProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
 <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><%=link_to "+ New Project",root_path,id:"logo-container",class:"brand-logo"%>
      <ul class="right hide-on-med-and-down">
        <%=render "partials/items"%>
      </ul>

      <ul id="nav-mobile" class="side-nav">
       	<%=render "partials/items"%>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  <script type="text/javascript">Materialize.toast('<%= notice %>', 6000, 'rounded')</script>
  <script type="text/javascript">Materialize.toast('<%= alert %>', 6000, 'rounded')</script>
<%= yield %>

<%= javascript_include_tag 'initm'%>
</body>
</html>

app/views/partials/_items.html.erb
<li><%=link_to "Inicio",root_path%></li>
<li><%=link_to "Explorar",projects_path%></li>
<%if current_user.nil?%>
  <li><%=link_to "Registrar",new_user_registration_path%></li>
  <li><%=link_to "Iniciar Sesión",new_user_session_path %></li>
  <%elsif%>
  <li><%= link_to "Cerrar Sesión",destroy_user_session_path, method: :delete%></li>
<%end%>
<li><a href="<%=evidencias_path%>">Evidencias</a></li>